# Day 2 - 13/11/2025: NumPy

In [1]:
import numpy as np

In [2]:
y = [1,2,3]
arr = np.array(y)

In [4]:
print(np.zeros(2))
print(np.ones(4))
print(np.arange(1,10))
print(np.linspace(1.,4.,6))
print(np.eye(3,3))
print(np.diag([1,2,3]))

[0. 0.]
[1. 1. 1. 1.]
[1 2 3 4 5 6 7 8 9]
[1.  1.6 2.2 2.8 3.4 4. ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [5]:
my_array = np.array([[[1, 2, 3],[4,5,6]],[[1.0, 2.0, 3.0],[4.0,5.0,6.0]]])
print(my_array.shape)
print(my_array.ndim)

(2, 2, 3)
3


In [8]:
a = np.array([1,2,3,4,5])
a_float = a.astype(np.float64)
print(a_float)

[1. 2. 3. 4. 5.]


In [9]:
my_array = np.array([[[1, 2, 3],[4,5,6]],[[1.0, 2.0, 3.0],[4.0,5.0,6.0]]])
print(my_array[0,1])
my_char_array = np.array([['a'],['b'],['c'],['d']])
print(my_char_array[1:]) 


[4. 5. 6.]
[['b']
 ['c']
 ['d']]


In [11]:
a = np.array([1,2,3,4,5,6])
a1 = a.reshape(2,3)
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
con = np.concatenate((a1,a2))
con

array([1, 2, 3, 4, 5, 6])

In [16]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
s= 5
print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.var(a))
print(np.argmin(a))
print(np.argmax(a))
r = s+a
print(r)

36
4.5
1
8
2.29128784747792
5.25
0
7
[ 6  7  8  9 10 11 12 13]


In [17]:
print(np.random.rand(3, 3))

[[0.12887366 0.45667137 0.59964804]
 [0.36621832 0.79069643 0.0135166 ]
 [0.59278647 0.41315206 0.99975522]]


In [21]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A+B)
print(A-B)
print(np.dot(A,B))
print(np.dot(B,A))
print(np.transpose(A))
inv = np.linalg.inv(A)
print(inv)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[19 22]
 [43 50]]
[[23 34]
 [31 46]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [22]:
original_array = np.array([1, 2, 3])
sliced_array = original_array[1:2]
#  changes in the sliced array affect the original array.
sliced_array *= 4
print(original_array) # [1,8,3]
print(sliced_array) # 8

[1 8 3]
[8]


In [23]:
array_1d = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
print(np.sort(array_1d))

[1 1 2 3 3 4 5 5 5 6 9]


In [24]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
print(np.vstack((array1, array2)))
print(np.hstack((array1, array2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [25]:
data = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt('output.txt', data, delimiter=',')