# Day 6 Basic statistics	

In [1]:
import numpy as np

In [2]:
data =[2,4,6,8,10,12,14,16,18,20,12]

In [3]:
np.mean(data)

np.float64(11.090909090909092)

In [4]:
np.median(data)

np.float64(12.0)

In [5]:
np.std(data)

np.float64(5.48476477418122)

In [6]:
x = [1, 2, 3, 4]
y = [2, 4, 6, 8]

np.corrcoef(x,y)[0,1]

np.float64(1.0)

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [10]:
print(arr.ndim)
print(arr[0][1])

2
2


In [11]:
print(arr[0][1]+arr[2][1])
print(arr[0][1]-arr[2][1])
print(arr[0][1]*arr[2][1])
print(arr[0][1]/arr[2][1])

10
-6
16
0.25


In [12]:
print(arr[-3:-1])
print(arr[1:3])

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]


In [13]:
arr.shape

(3, 3)

In [16]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
newarr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [18]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]
