In [1]:
import numpy as np

In [2]:
data_emp = np.array([
    [42, 10, 2, 35000],
    [38, 8, 1, 32000],
    [45, 12, 3, 40000],
    [36, 9, 0, 30000],
    [48, 15, 4, 42000],
    [40, 11, 2, 36000],
    [44, 13, 1, 39000]
])

In [3]:
columns_emp = np.array(['Hours_Worked', 'Tasks_Completed', 'Errors', 'Salary'])

In [4]:
print("Employee Data:\n", data_emp)
print("\nColumns:", columns_emp)

Employee Data:
 [[   42    10     2 35000]
 [   38     8     1 32000]
 [   45    12     3 40000]
 [   36     9     0 30000]
 [   48    15     4 42000]
 [   40    11     2 36000]
 [   44    13     1 39000]]

Columns: ['Hours_Worked' 'Tasks_Completed' 'Errors' 'Salary']


In [5]:
print("Shape:", data_emp.shape)
print("Data Type:", data_emp.dtype)

Shape: (7, 4)
Data Type: int64


In [6]:
total_tasks = np.sum(data_emp[:, 1])
print("Total tasks completed:", total_tasks)

Total tasks completed: 78


In [7]:
avg_salary = np.mean(data_emp[:, 3])
print("Average Salary:", avg_salary)

Average Salary: 36285.71428571428


In [8]:
print("Std Dev of Salary:", np.std(data_emp[:, 3]))

Std Dev of Salary: 4025.4293724586773


In [9]:
print("Max Salary:", np.max(data_emp[:, 3]))
print("Min Salary:", np.min(data_emp[:, 3]))

Max Salary: 42000
Min Salary: 30000
